# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script into the container
COPY app.py /app/app.py

# Run the Python script when the container starts
CMD ["python", "app.py"]